//! Wire protocol between the REAPER extension and the app (SPEC §2.2).
//! The types here are the single source for the UI's TypeScript types (WP 0.4).

mod action_choice;
mod appearance_choice;
mod catalog;
mod check_id;
mod check_item;
mod check_status;
mod checklist_view;
mod command;
mod cue_info;
mod entry_info;
mod event_record;
pub mod frame;
mod import_offer;
mod installation_view;
mod link_problem;
mod link_status;
mod link_view;
mod live;
pub mod message;
mod note_mapping;
mod notice;
mod notice_level;
mod phase;
mod setlist_info;
mod setlist_transfer_view;
mod setting;
mod settings;
mod settings_view;
mod song_info;
mod system_stats;
mod transport;
mod wire_event;
mod wizard_step;
mod wizard_step_id;
mod wizard_step_status;

#[cfg(test)]
mod generated;

pub use action_choice::ActionChoice;
pub use appearance_choice::AppearanceChoice;
pub use catalog::Catalog;
pub use check_id::CheckId;
pub use check_item::CheckItem;
pub use check_status::CheckStatus;
pub use checklist_view::ChecklistView;
pub use command::Command;
pub use cue_info::CueInfo;
pub use entry_info::EntryInfo;
pub use event_record::EventRecord;
pub use import_offer::ImportOffer;
pub use installation_view::InstallationView;
pub use link_problem::LinkProblem;
pub use link_status::LinkStatus;
pub use link_view::LinkView;
pub use live::Live;
pub use note_mapping::NoteMapping;
pub use notice::Notice;
pub use notice_level::NoticeLevel;
pub use phase::Phase;
pub use setlist_info::SetlistInfo;
pub use setlist_transfer_view::SetlistTransferView;
pub use setting::Setting;
pub use settings::Settings;
pub use settings_view::SettingsView;
pub use song_info::SongInfo;
pub use system_stats::SystemStats;
pub use transport::Transport;
pub use wire_event::WireEvent;
pub use wizard_step::WizardStep;
pub use wizard_step_id::WizardStepId;
pub use wizard_step_status::WizardStepStatus;
