//! Reaper Control app: the Tauri shell around the app core.

mod app_config;
mod app_event;
mod app_fault;
mod appearance_config;
mod apply_event;
mod binary_architecture;
mod chaos_proxy;
mod chaos_settings;
mod clock;
mod command_bus;
mod command_check;
mod command_queue;
mod command_refusal;
mod config_error;
mod config_location;
mod config_migration;
mod config_repository;
mod config_store;
mod diagnostics_bundle;
mod diagnostics_error;
mod dispatch_error;
mod driver;
mod driver_error;
mod endpoint_location;
mod event_bus;
mod event_logger;
mod extension_installer;
mod extension_preparer;
mod fake_clock;
mod fake_config_repository;
mod fake_driver;
mod fake_extension;
mod fake_fault_check;
mod fake_midi_source;
mod fake_mirror_repository;
mod fake_process_check;
mod fake_stats_source;
mod fault_check;
mod fault_file_check;
mod health_monitor;
mod import_error;
mod install_action;
mod install_error;
mod install_item;
mod install_item_kind;
mod install_plan;
mod install_platform;
mod install_report;
mod install_status;
mod install_verification;
mod intent;
mod intent_dispatcher;
mod intent_error;
mod intent_refusal;
mod intent_translator;
mod journal_import;
mod latency_stats;
mod legacy_config_file;
mod legacy_config_import;
mod legacy_file;
mod legacy_item;
mod legacy_midi;
mod legacy_resolver;
mod legacy_setlist;
mod link_cause;
mod link_connection;
mod link_health;
mod link_pipeline;
mod link_session;
mod link_view_source;
mod log_config;
mod logging;
mod mac_extension_preparer;
mod message_translator;
mod metered_driver;
mod midi_config;
mod midi_debounce;
mod midi_device_follower;
mod midi_listener;
mod midi_message;
mod midi_router;
mod midi_source;
mod midi_switch;
mod midir_source;
mod mirror_error;
mod mirror_file;
mod mirror_keeper;
mod mirror_repository;
mod notice_for_event;
mod panic_hook;
mod pending_command;
mod performance_runs;
mod periodic_thread;
mod plain_extension_preparer;
mod process_check;
mod queue_config;
mod queue_rejection;
mod queue_settings;
mod reaper_folder_argument;
mod reaper_install;
mod resolved_setlist;
mod setlist_mirror;
mod setlist_transfer;
mod settings_service;
mod shell;
mod shutdown_sequence;
mod simulator;
mod start_link;
mod stats_source;
mod sysinfo_stats_source;
mod system_clock;
mod system_process_check;
mod system_stats_service;

pub use app_config::{AppConfig, SCHEMA_VERSION};
pub use app_event::AppEvent;
pub use app_fault::AppFault;
pub use appearance_config::{AppearanceConfig, DENSITIES, THEMES, TOUCH_SIZES};
pub use apply_event::apply_event;
pub use binary_architecture::BinaryArchitecture;
pub use chaos_proxy::ChaosProxy;
pub use chaos_settings::ChaosSettings;
pub use clock::Clock;
pub use command_bus::CommandBus;
pub use command_check::check;
pub use command_queue::CommandQueue;
pub use command_refusal::CommandRefusal;
pub use config_error::ConfigError;
pub use config_location::{
    config_file, diagnostics_directory, legacy_config_file, legacy_setlists_directory,
    log_directory, mirror_directory,
};
pub use config_migration::migrate;
pub use config_repository::ConfigRepository;
pub use config_store::ConfigStore;
pub use diagnostics_bundle::DiagnosticsBundle;
pub use diagnostics_error::DiagnosticsError;
pub use dispatch_error::DispatchError;
pub use driver::Driver;
pub use driver_error::DriverError;
pub use endpoint_location::{endpoint_file, endpoint_file_from, extension_directory, fault_file};
pub use event_bus::EventBus;
pub use event_logger::log_event;
pub use extension_installer::ExtensionInstaller;
pub use extension_preparer::ExtensionPreparer;
pub use fake_clock::FakeClock;
pub use fake_config_repository::FakeConfigRepository;
pub use fake_driver::FakeDriver;
pub use fake_extension::FakeExtension;
pub use fake_fault_check::FakeFaultCheck;
pub use fake_midi_source::FakeMidiSource;
pub use fake_mirror_repository::FakeMirrorRepository;
pub use fake_process_check::FakeProcessCheck;
pub use fake_stats_source::FakeStatsSource;
pub use fault_check::FaultCheck;
pub use fault_file_check::FaultFileCheck;
pub use health_monitor::HealthMonitor;
pub use import_error::ImportError;
pub use install_action::InstallAction;
pub use install_error::InstallError;
pub use install_item::InstallItem;
pub use install_item_kind::InstallItemKind;
pub use install_plan::InstallPlan;
pub use install_platform::InstallPlatform;
pub use install_report::InstallReport;
pub use install_status::InstallStatus;
pub use install_verification::InstallVerification;
pub use intent::Intent;
pub use intent_dispatcher::IntentDispatcher;
pub use intent_error::IntentError;
pub use intent_refusal::IntentRefusal;
pub use intent_translator::IntentTranslator;
pub use journal_import::JournalImport;
pub use latency_stats::LatencyStats;
pub use legacy_config_file::LegacyConfigFile;
pub use legacy_config_import::import_legacy_config;
pub use legacy_file::LegacyFile;
pub use legacy_item::LegacyItem;
pub use legacy_midi::LegacyMidi;
pub use legacy_resolver::resolve;
pub use legacy_setlist::LegacySetlist;
pub use link_cause::LinkCause;
pub use link_connection::LinkConnection;
pub use link_health::LinkHealth;
pub use link_pipeline::LinkPipeline;
pub use link_session::LinkSession;
pub use link_view_source::LinkViewSource;
pub use log_config::{LEVELS, LogConfig};
pub use logging::Logging;
pub use mac_extension_preparer::MacExtensionPreparer;
pub use message_translator::MessageTranslator;
pub use metered_driver::MeteredDriver;
pub use midi_config::MidiConfig;
pub use midi_debounce::MidiDebounce;
pub use midi_device_follower::MidiDeviceFollower;
pub use midi_listener::MidiListener;
pub use midi_message::MidiMessage;
pub use midi_router::MidiRouter;
pub use midi_source::{MidiConnection, MidiSource};
pub use midi_switch::MidiSwitch;
pub use midir_source::MidirSource;
pub use mirror_error::MirrorError;
pub use mirror_file::MirrorFile;
pub use mirror_keeper::MirrorKeeper;
pub use mirror_repository::MirrorRepository;
pub use notice_for_event::{link_problem, notice_for_event};
pub use panic_hook::{describe, install_panic_hook};
pub use pending_command::PendingCommand;
pub use performance_runs::performance_runs;
pub use periodic_thread::PeriodicThread;
pub use plain_extension_preparer::PlainExtensionPreparer;
pub use process_check::ProcessCheck;
pub use queue_config::QueueConfig;
pub use queue_rejection::QueueRejection;
pub use queue_settings::QueueSettings;
pub use reaper_folder_argument::reaper_folder_argument;
pub use reaper_install::ReaperInstall;
pub use resolved_setlist::ResolvedSetlist;
pub use setlist_mirror::SetlistMirror;
pub use setlist_transfer::SetlistTransfer;
pub use settings_service::SettingsService;
pub use shell::run;
pub use shutdown_sequence::ShutdownSequence;
pub use simulator::{Simulator, sample_project};
pub use start_link::start_link;
pub use stats_source::StatsSource;
pub use sysinfo_stats_source::SysinfoStatsSource;
pub use system_clock::SystemClock;
pub use system_process_check::SystemProcessCheck;
pub use system_stats_service::SystemStatsService;
