/**
 * Every word the interface shows, in one place, so a translation can replace this module
 * in v2.1. Components and view logic import from here and hold no copy of their own
 * (`strings.test.ts` checks the components). Wording follows v1 where v1 had it.
 */

const plural = (count: number, one: string, many: string): string => `${count} ${count === 1 ? one : many}`;

export const strings = {
  app: { name: "Reaper Control" },

  screens: {
    player: "Player",
    setlists: "Setlists",
    checklist: "Pre-show check",
    settings: "Settings",
    help: "Help",
    performerMode: "Performer mode",
    mainNavigation: "Main",
  },

  setlists: {
    title: "Setlists",
    listLabel: "Setlists in this project",
    none: "This project has no setlist yet.",
    create: "New setlist",
    newName: "New setlist",
    name: "Name",
    playing: "Playing",
    play: "Play this setlist",
    songs: (count: number) => (count === 1 ? "1 song" : `${count} songs`),
    entriesLabel: "Songs in this setlist",
    empty: "No songs yet. Add one below.",
    projectSongs: "Songs in project",
    search: "Search songs",
    addSong: (name: string) => `Add ${name}`,
    noSongsFound: "No song matches.",
    meta: (count: number, time: string) => `${count === 1 ? "1 song" : `${count} songs`} · ${time}`,
    missingBanner: (count: number) => `${count === 1 ? "1 song is" : `${count} songs are`} missing in the REAPER project. Fix it before you perform.`,
    editorLabel: "Setlist entries",
    savedHint: "Saved in the REAPER project",
    noTime: "--:--",
    listMeta: (count: number, playing: boolean) => `${count === 1 ? "1 song" : `${count} songs`}${playing ? " · Playing" : ""}`,
    remove: (name: string) => `Remove ${name}`,
    moveUp: (name: string) => `Move ${name} up`,
    moveDown: (name: string) => `Move ${name} down`,
    missing: "Not in the project",
    missingSong: "This song is no longer in the project",
    save: "Save setlist",
    discard: "Discard changes",
    nameNeeded: "Give the setlist a name.",
    changedInReaper: "This setlist was changed in REAPER while you were editing.",
    reload: "Load the REAPER version",
    unsaved: "Unsaved changes",
    delete: "Delete setlist",
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteWarning: "The setlist is removed from the project. The songs themselves stay.",
    deleteWasPlaying: "It is the setlist that is playing; the songs will play in timeline order again.",
    deleteConfirm: "Delete",
    deleteCancel: "Keep it",
  },

  connection: {
    notRunning: "REAPER not running",
    waitingForExtension: "waiting for the extension",
    seeMessage: "we keep trying",
    updateExtension: "click to update it",
    outdated: "Extension out of date",
    connected: "Connected to REAPER",
    disconnected: "Disconnected",
    extensionVersion: (version: string) => `extension ${version}`,
  },

  midiStatus: {
    connected: "MIDI connected",
    notConnected: "MIDI not connected",
    noneFound: "No MIDI found",
    connectIt: "connect it, we keep looking",
    plusMore: (name: string, more: number) => `${name} and ${more} more`,
  },

  wizard: {
    title: "Set up the connection",
    intro: "Reaper Control talks to REAPER through a small extension. This puts it in place and checks that it answers.",
    steps: {
      FindReaper: "Find REAPER",
      InstallExtension: "Install the extension",
      RestartReaper: "Restart REAPER",
      Connect: "Connect",
    },
    status: { Done: "Done", Current: "Now", Waiting: "Later", NeedsYou: "Needs you" },
    install: "Install the extension",
    installing: "Installing",
    checkAgain: "Check again",
    folder: "REAPER's folder",
    copyFolder: "Copy the folder path",
    copied: "Copied",
    done: "Connected. You are ready.",
    finish: "Continue",
    skip: "Skip for now",
    stepOf: (step: number, count: number) => `STEP ${step} OF ${count}`,
    stepsLabel: "Steps",
    connection: { title: "Connection", hint: "The extension lets this app control REAPER. Run the setup again to repair it.", open: "Open the setup" },
  },

  checklist: {
    title: "Pre-show check",
    intro: "Look this over before you go on stage. It updates by itself.",
    checks: {
      ExtensionCurrent: "Extension up to date",
      Connected: "Connected to REAPER",
      SongsFound: "Songs found",
      SetlistValid: "Setlist valid",
      MidiPresent: "MIDI present",
    },
    status: { Passed: "OK", Failed: "Fix this", Skipped: "Not checked" },
    ready: "Ready for the show.",
    notReady: "Not ready: fix the rows marked \"Fix this\".",
    checkAgain: "Check again",
    openSetup: "Open the setup",
    readyTitle: "Ready",
    attentionTitle: "Not ready yet",
    counts: (passed: number, failed: number) =>
      `${passed === 1 ? "1 check passed" : `${passed} checks passed`}, ${failed === 0 ? "none needs" : failed === 1 ? "1 needs" : `${failed} need`} your attention.`,
    performAnyway: "Perform anyway",
    perform: "Open Performer mode",
    fixInSetlists: "Fix in Setlists",
    checksLabel: "Checks",
  },

  help: {
    title: "Help",
    intro: "How to set up REAPER for this app, and how to mark your songs.",
    topics: "Help topics",
    sections: [
      {
        id: "connect",
        title: "Connect the app",
        steps: [
          "Open Settings and run the setup. It finds REAPER, installs the extension and asks you to restart REAPER.",
          "Open REAPER with your project. The app connects by itself: the dot in the sidebar turns green.",
          "If it does not connect, check that REAPER is running and open the Pre-show check to see what fails.",
        ],
      },
      {
        id: "songs",
        title: "Songs and cues",
        steps: [
          "Every region in your project is a song. Name the regions as you want them on stage.",
          "To make a region, drag over the ruler and press Shift+R. Double-click the region to name it.",
          "Every marker is a cue, a point you can jump to. Press M to add one.",
        ],
      },
      {
        id: "markers",
        title: "Special markers",
        intro: "Put a token in the name of a marker or region. Tokens can be combined, in any order, separated by spaces. A marker that holds only tokens is not shown on the timeline.",
        cards: [
          { code: "!1008", name: "Hard stop", text: "The show stops at the end of the song until you press play again. Also written !hardstop. The marker may lie anywhere inside the song.", tone: "stop" },
          { code: "!length:45", name: "Custom length", text: "The song counts as 45 seconds, for the hard stop and the setlist time. Use it with a hard stop.", tone: "length" },
          { code: "!bpm:120", name: "Starting tempo", text: "The tempo shown for the song. Put it at the very start of the song. It does not change REAPER's tempo.", tone: "tempo" },
        ],
        example: "!length:45 !bpm:140 !1008",
      },
      {
        id: "count-in",
        title: "Count-in",
        steps: [
          "Switch on Count-in when pressing marker, then press a cue: the app jumps there and REAPER counts in.",
          "The count-in uses REAPER's tempo and its Count-in measures setting.",
        ],
      },
      {
        id: "midi",
        title: "MIDI control",
        steps: [
          "Open Settings and switch on MIDI. Choose your device or leave it on all devices.",
          "Add a mapping: a note number from 0 to 127 and the action it triggers.",
        ],
      },
    ],
  },


  health: {
    title: "Connection and health",
    close: "Close",
    open: "Connection details",
    machineCpu: "Machine CPU",
    machineMemory: "Machine memory",
    appMemory: "This app",
    reaperMemory: "REAPER",
    notFound: "not found",
    megabytes: (value: number) => `${value} MB`,
    loadFailed: "The numbers could not be read.",
  },

  performer: {
    noSong: "No Song Selected",
    setlist: (name: string) => `Setlist: ${name}`,
    songTime: "Song:",
    totalTime: "Total:",
    countIn: "Count-in",
    next: (name: string) => `Next: ${name}`,
    endOfSetlist: "End of setlist",
    duration: (time: string) => `Duration: ${time}`,
    pressPlay: "Press play to continue",
    exit: "Exit Performer Mode",
    lock: "Lock screen",
    unlock: "Unlock",
    unlockAgain: "Tap again to unlock",
    locked: "Screen locked",
    autoResume: (on: boolean) => `Auto-resume: ${on ? "ON" : "OFF"}`,
    countInOnMarker: (on: boolean) => `Count-in when pressing marker: ${on ? "ON" : "OFF"}`,
    previous: "Previous song",
    rewind: "Rewind to start of song",
    play: "Play",
    pause: "Pause",
    nextSong: "Next song",
    toggleRecording: "Toggle recording",
    hardStopPoint: "Hard stop point",
    systemStatus: "System status",
    midiActivity: "MIDI activity",
    cpu: (percent: number) => `CPU ${percent}%`,
  },

  player: {
    songs: "Songs in the setlist",
    noSetlist: "No setlist is being played. Choose one on the Setlists screen.",
    current: "Playing now",
    next: "Next",
    played: "Played",
    bpm: (value: number) => `${Math.round(value)} BPM`,
    hardStop: "Hard stop",
    controls: "Transport",
    settings: "Behaviour",
    setlist: "Setlist",
    chooseSetlist: "Choose the setlist to play",
    noSetlistChosen: "No setlist",
    nowPlaying: (position: number, count: number) => `NOW PLAYING · ${position} OF ${count}`,
    ready: (count: number) => `READY · ${count} SONGS`,
    tempo: "TEMPO",
    bpmUnit: "BPM",
    time: "TIME",
    options: "OPTIONS",
    optionsLabel: "Options",
    armRecording: "Arm recording",
    autoResume: "Auto-resume playback",
    countInOnMarker: "Count-in when pressing marker",
    songsTitle: "Songs",
    inSetlist: (count: number) => `· ${count} in setlist`,
    hardStopTag: "HARD STOP",
  },

  pending: { sending: "Sending…" },
  notices: { dismiss: "Dismiss" },

  settings: {
    title: "Settings",
    save: "Save",
    discard: "Discard changes",
    saved: "Saved. Everything applies now except the log level, which applies after a restart.",
    mustBeWhole: (label: string) => `${label} must be a whole number`,
    milliseconds: (label: string) => `${label} (ms)`,
    fields: { repeatWindow: "Repeat window", timeout: "Timeout", queueSize: "Queue size", debounce: "Debounce" },
    midi: {
      title: "MIDI control",
      hint: "Trigger actions from a foot controller or keyboard. Changes apply at once.",
      enabled: "Enabled",
      device: "Device",
      allDevices: "All devices",
      channel: "Channel",
      allChannels: "All channels",
      note: "Note",
      action: "Action",
      noteRange: "Note must be between 0 and 127",
      noteTwice: (note: number) => `Note ${note} is used twice`,
      add: "Add a note",
      remove: (note: string) => `Remove note ${note}`,
      empty: "No notes yet. Add one to control the app from a controller.",
    },
    queue: {
      title: "Command queue",
      hint: "How the app guards the commands it sends to REAPER. Applies at once.",
    },
    appearance: {
      title: "Appearance",
      hint: "How the screens look. Applies at once when you save.",
      theme: "Theme",
      density: "Density",
      touch: "Touch targets",
      themes: { dark: "Dark", "stage-dark": "Stage dark", light: "Light" } as Record<string, string>,
      densities: { comfortable: "Comfortable", compact: "Compact" } as Record<string, string>,
      touchSizes: { normal: "Normal", large: "Large" } as Record<string, string>,
    },
    diagnostics: {
      title: "Diagnostics",
      hint: "The log has the app's lines and the hand-over journal from REAPER. Export one zip to send when something went wrong. The log level applies after a restart.",
      logLevel: "Log level",
      export: "Export diagnostics",
      savedTo: (path: string) => `Saved to ${path}`,
    },
    transfer: {
      title: "Setlists backup and v1 import",
      hint: "The app keeps a copy of this project's setlists. Bring back a lost setlist, or take over the ones you made in v1.",
      refresh: "Refresh",
      backup: "Backup copy",
      nothingToRestore: "Nothing to restore: the project has every setlist the copy has.",
      missing: (names: string) => `Missing from the project: ${names}`,
      restore: (count: number) => `Restore ${count}`,
      fromV1: "From v1",
      nothingToImport: "No v1 setlists to import for this project.",
      import: (count: number) => `Import ${count}`,
      songs: (count: number) => plural(count, "song", "songs"),
      notInProject: (found: string, names: string) => `${found}; not in this project: ${names}`,
      nothingTo: (what: string) => `Nothing to ${what}.`,
      done: (count: number, past: string) => `${plural(count, "setlist", "setlists")} ${past}.`,
      restored: "restored",
      imported: "imported",
    },
  },
} as const;
